format = """
$os\
$directory\
[ ](fg:#88C0D0 bg:#1d2230)\
$git_branch\
$git_status\
[ ](fg:#1d2230)\
$fill\
$python\
$lua\
\n$character
"""

right_format = """
$cmd_duration\
$username\
✨
$time
"""

# コマンドラインに1行分のスペースを入れる
add_newline = true

[os.symbols]
Macos = "  "
Linux = " 󰌽 "
Ubuntu = "  "
Debian = "  "

[os]
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false


# left_promptとright_promptの間を何で埋めるか設定
[fill]
symbol = ' '
style = 'fg:#01242e bg:none'

[directory]
style = "fg:#2E3440 bg:#88C0D0 bold"
# format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
# truncation_symbol = ' ' # nf-fa-folder_open
# truncate_to_repo = false
# style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[ $path ]($style)[$read_only]($read_only_style)'


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#1d2230)]($style)'

[git_status]
style = "bg:#1d2230"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#1d2230)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[$duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
format = '[[   $time ](fg:#a0a9cb)]($style)'

[character]
vimcmd_symbol = '[V](bold green)'

[python]
pyenv_version_name = false
symbol = '[ ](fg:#f9e2af bg:#8093fd)'
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
style = 'bold fg:#313244 bg:#8093fd'

# 実際にアクティブな環境だけ表示
detect_env_vars = ['VIRTUAL_ENV', 'CONDA_DEFAULT_ENV']

# ここで .venv 検出を完全無効化
detect_folders = []
detect_files = []
[lua]
symbol = "[ ](fg:#1e66f5 bg:#89b4fa)"
format = '[ ](fg:#89b4fa)[ ${symbol}(${version})]($style)[ ](fg:#89b4fa)'
style = 'bold fg:#313244 bg:#89b4fa'
